### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by k10876** [us/english-please#12]
Truly enough, your repo helps developers translate their README.md.
But, there are some suggestions I'd like to give:
1. We Chinese are able to translate English when we see them. In the same way, English speakers should also have the ability to translate Chinese. You can also use Google Translate to translate them because we also use them when we read English READMEs.
2. Some of the repos on Github are focused on problems in Chinese, such as Baidu Netdisk and Netease Music. These repos are used to help Chinese, and we are sure that you don't use them for daily use. So, English READMEs is not needed.

**Comment by k10876** [comment]
These are my suggestions on your project.
If you are against me, you can close this issue.
Thanks.

**Comment by pys078** [comment]
Absoulutely right.
We sometimes also need Chinese README because many  english READMEs are too long to understand in one attemp,maybe just for me.
But in fact,in chinese culture,people intend to solve things like that through one's own ability compared with seeking for the native speakers' help ,which is considered a little bit disgrace.
As for Baidu Netdisk and Netease Music,i dare say that if you are a chinese,you will never avoid using them,but in some aspects,they really sucks.

**Comment by Jamim** [comment]
Hello @k10876 and @pys078,
Unfortunately, `Google Translate`ed READMEs are not so clear as manually translated ones.

**Comment by pys078** [comment]
@Jamim I understand that.So why not just make some chinese friends to make it easier?XD😂

**Comment by k10876** [comment]
You could learn to speak Chinese(although it's hard and I know it may be impossible). :)

**Comment by k10876** [comment]
> Hello @k10876 and @pys078,
> Unfortunately, `Google Translate`ed READMEs are not so clear as manually translated ones. 

It is. We know that it's not clear. We use Google Translate and have the same problem when we are translating English. I think you could guess what the translation means. 😄

**Comment by k10876** [comment]
> Absoulutely right.
> We sometimes also need Chinese README because many english READMEs are too long to understand in one attemp,maybe just for me.
> But in fact,in chinese culture,people intend to solve things like that through one's own ability compared with seeking for the native speakers' help ,which is considered a little bit disgrace.
> As for Baidu Netdisk and Netease Music,i dare say that if you are a chinese,you will never avoid using them,but in some aspects,they really sucks.
> Tips: There are 16 problems here on Grammarly. 😃 

That's right. I agree with you.
By the way, Baidu Netdisk is the thing we want to avoid, but we are forced to use them.

**Comment by k10876** [comment]
Well, I think this program is good, and we can make another one called `"Chinese Please"`, right?

**Comment by k10876** [comment]
I got some ideas for this.
I'm gonna fork this and make another repo called "Chinese Please".
Also, I will make a Chinese README for this repo and help Chinese Users.
This repo is really useful for both Chinese Users (who can't understand English) and English Users (who can't understand Chinese).

**Comment by ghost** [comment]
**Affirmative!** We are supposed to make README in English rather than Chinese for English is a worldwide language although Chinese has always been  the best language since the human beings created.

**Comment by jioushan** [comment]
Searching US on github let me see this issue. Very interesting, I admit, we did help me understand READMEs better through translation plugins.
You want to try to translate CN to EN. ummmmm
This is the case, good projects usually do have EN, CN, JP and other languages, and even the developer team will make them for them. But for those mediocre projects, I think its existence is really monotonous. In the past few years, English was still dominant on the Internet. Currently too.
Mentioned earlier, Baidu Pan. netease music. aha. Maybe you are right, the vast majority of Chinese users do use such products. But there are also a small number of people who choose others.
Search engines cannot be monopolized by Google alone. I still choose other third-party search engines as my second alternative.
you.com
Qwant.com
yahoo.co.jp
I personally prefer music software
Spotify and Apple music
ummmmmm
About Baidu Pan. I think. At present, I use a private network disk storage hosted by a server or public cloud storage.

One thing is true, when a product is bad, I think people with strong hands-on skills will make a more usable product.
In particular, the market will continue to compete, and many companies will have competing products in their sub-brand sub-sectors.

No matter how much social software there are, I still choose email as the most important communication method.

Sorry, some talked too much.
