### ISSUE TITLE
Why can't we use Google Translate?

### ISSUE THREAD

**Issue by censujiang** [us/english-please#17]
I am a Chinese and I like to find active and practical open source programs on github. Why can't we use Google Translate to solve language problems among programmers from various countries?

Some programs are in line with China's national conditions, such as the 12306 ticket grab plug-in, which is not very useful for programmers in other countries.

Oh, and by the way, 12306 is a train ticket sales platform in charge of the China Railway Administration.

**Comment by us** [comment]
#12
