### ISSUE TITLE
Three issues about this repo

### ISSUE THREAD

**Issue by ijkzen** [us/english-please#8]
1. The meaning of README-zh_CN.md is exactly the opposite of README.md, whose meaning is "Chinese Please".
2. There is a URL at the end of issue_body.md, which should add "https://" prefix, otherwise will be 404.
3. Don't complain, Chinese is also international.

**Comment by us** [comment]
Thanks for reporting 
1. I trusted him and don't translate to english, it's my mistake so thanks for warning! I delete it.
2. Thank you fixed.
3. I don't complain, it's just an offer. Also english repos should add the chinese readmes'. The purpose of open source is to share knowledge and influence the more people the better.
So basically it would be better if it reaches more people.
